### ISSUE TITLE
can not delete route after delete node

### ISSUE THREAD

**Issue by okko123** [yzxiu/calico-route-sync#1]
K8S-1.24.16
calico 3.26.1
OS: CentOS 7.9.2009
kernel: Linux centos-1 3.10.0-1160.el7.x86_64

client: Ubuntu 22.04.2
kernel: Linux ansible 5.15.0-78-generic

k8s cluster use 4 node
[root@centos-1 ~]# kubectl get nodes
NAME       STATUS   ROLES           AGE     VERSION
centos-1   Ready    control-plane   5h44m   v1.24.16
centos-2   Ready    <none>          5h41m   v1.24.16
centos-3   Ready    <none>          5h41m   v1.24.16
centos-4   Ready    <none>          5h41m   v1.24.16

when i delete node
kubectl node centos-4
kubectl node centos-3

but in the client still have route to centos-4 centos-3
nuc@ansible:~$ ip route
default via 172.16.81.254 dev ens160 proto static
172.16.30.0/24 dev ens192 proto kernel scope link src 172.16.30.150
172.16.81.0/24 dev ens160 proto kernel scope link src 172.16.81.150
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.16.128/26 via 172.16.30.103 dev ens192
192.168.43.128/26 via 172.16.30.102 dev ens192
192.168.161.0/26 via 172.16.30.101 dev ens192
192.168.217.192/26 via 172.16.30.104 dev ens192

stop calico-route-sync-linux, the route still on client
nuc@ansible:~$ ip route
default via 172.16.81.254 dev ens160 proto static
172.16.30.0/24 dev ens192 proto kernel scope link src 172.16.30.150
172.16.81.0/24 dev ens160 proto kernel scope link src 172.16.81.150
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.16.128/26 via 172.16.30.103 dev ens192
192.168.217.192/26 via 172.16.30.104 dev ens192

**Comment by yzxiu** [comment]
Thank you!  :-)
